[build]
  base = "Amazon-Clone"                       # where your frontend code is
  publish = "dist"               # output folder after `npm run build`
  functions = "/netlify/functions"  # folder for Netlify serverless functions
  command = "npm install && npm run build"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

 
